### ISSUE TITLE
Bible Translation History

### ISSUE THREAD

**Issue by sundeep2413** [BibleBot/BibleBot#255] opened 2022-02-22 22:59 UTC
### What would you like to see implemented in BibleBot?

With each of the bible versions - maybe add a history of how this version came to be.

Status can include: Version, How Old the Version, Who Wrote It?, and Connection to it journey of making it
> For the connection to the journey citing to a correct site is more efficient and

**Comment by SeraphimRP** [comment] 2022-02-22 23:27
Duplicate of #247, closing...

**Closed by SeraphimRP** 2022-02-22 23:27 UTC
Labels: duplicate
