### ISSUE TITLE
The Knox Bible, please!

### ISSUE THREAD

**Issue by Cullen98** [BibleBot/BibleBot#302] opened 2022-07-05 16:58 UTC
### What Bible version would you like to see added in BibleBot?

I'd greatly appreciate if "The Holy Bible: A Translation From the Latin Vulgate in the Light of the Hebrew and Greek Originals" also known as the Knox Translation, was added

**Comment by SeraphimRP** [comment] 2022-07-05 19:51
Duplicate of #288, closing...

**Closed by SeraphimRP** 2022-07-05 19:51 UTC
Labels: translation::request
